spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

elastic:
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  host: ${ELASTIC_HOST}
  port: ${ELASTIC_PORT}
  truststore:
    location: ${ELASTIC_TRUSTSTORE_LOCATION}
    password: ${ELASTIC_TRUSTSTORE_PASSWORD:}