server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    include: value, secret
  datasource:
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: Spring-HikariPool
      max-lifetime: 60000
      maximum-pool-size: 30
    userlock:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: UserLock-HikariPool
      max-lifetime: 60000
      maximum-pool-size: 20
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  messages:
    basename: message.messages
  data:
    redis:
      host: ${SPRING.REDIS_HOST}
      port: 6379
logging:
  level:
    root: info
