quest:
  page:
    size: 20

security:
  url:
    allowed_url: ["/", "/css/**", "/js/**", "/image/**", "/error", "/api/v1/auth/**"]
    admin_url: ["/admin/**"]
    logout_url: "/api/v1/auth/logout"
  origin:
    allowed_origin: ["http://localhost:9090", "http://dailyquest.mooo.com"]

spring:
  jwt:
    secret: ${JWT_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}

redis:
  key:
    exp_table: ${REDIS_EXP_TABLE_KEY}
    nickname_prefix: ${REDIS_NICKNAME_PREFIX_KEY}
    nickname_postfix: ${REDIS_NICKNAME_POSTFIX_KEY}
    settings: ${REDIS_SETTINGS_KEY}
    quest_clear_exp: ${REDIS_QUEST_CLEAR_EXP_KEY}
    quest_clear_gold: ${REDIS_QUEST_CLEAR_GOLD_KEY}
    max_reward_count: ${REDIS_MAX_REWARD_COUNT_KEY}

elastic:
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  host: ${ELASTIC_HOST}
  port: ${ELASTIC_PORT}
